name: indrapose-webapp
version: '1.0.1-ctrlx'
base: core22
summary: POC pour IHM nouvelle version indrapose
description: |
      L'objectif de cette application est de vérifier la faisabilité de passer par une app SDK pour l'IHM pour la nouvelle version d'Indrapose. L'utilisateur génère un script G-code qui sera interprété par https://community.boschrexroth.com/ctrlx-automation-how-tos-qmglrz33/post/how-to-use-g-code-ui-on-ctrlx-core-ViG9UrH7C4zAZuk
      Code source : https://github.com/Felix-73/CTRLX-SDK-APP-Indrapose-poc.git
confinement: strict
grade: stable
architectures:
  - build-on: [amd64, arm64]
    build-for: [amd64]
  - build-on: [amd64, arm64]
    build-for: [arm64]

    
apps:
 
  flask-server: 
    command: bin/runserver.wrapper  
    plugs:
      - network-control
      - network-observe
      - network
      - network-bind
    daemon: simple 
    
  desktop-launch:
    command: bin/desktop-launch
    plugs:
      - desktop  

parts:

  flask:
    plugin: python
    build-environment:
      - PYTHONPATH: "$SNAPCRAFT_PART_INSTALL/usr/lib/python3/dist-packages"
    python-packages: 
      - flask
    source: .
  
  python-code:  
    source: ./Flask/
    plugin: dump
    organize:
      '*': bin/Flask/

  shscripts:  
    source: ./shscripts/
    plugin: dump
    organize:
      '*': bin/

  configs:
    plugin: dump
    source: ./configs
    organize:
      'package-assets/*': package-assets/${SNAPCRAFT_PROJECT_NAME}/

slots:
  package-assets:
    interface: content
    content: package-assets
    source:
      read:
        - $SNAP/package-assets/${SNAPCRAFT_PROJECT_NAME}
  package-run:
    interface: content
    content: package-run
    source:
      write:
        - $SNAP_DATA/package-run/${SNAPCRAFT_PROJECT_NAME}

# pour générer le fichier dans app data
plugs:
  active-solution:
    interface: content
    content: solutions
    target: $SNAP_COMMON/solutions